name: release

on:
  release:
    types: [published]
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Package Version
        run: echo "VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)" >> $GITHUB_OUTPUT
        id: package

      - name: Valid Release Tag
        run: |
          if ${{ github.ref_name }} != ${{ steps.package.outputs.VERSION }} ; then
            echo "Looks like you forgot to bump the package version? Current package version: ${{ steps.package.outputs.VERSION }} incompatible with tag: ${{ github.ref_name }}"
            exit 1
          fi
          
      - uses: actions/setup-node@v3
        with: 
          cache: npm
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@chrillaz'
          
      - run: npm ci
      - run: npm publish